import React, { createContext, useContext, useState, useEffect } from 'react';

const LANGS = {
  vi: {
    flag: '🇻🇳',
    label: 'VI',
    sb_sub: 'Hội viên doanh nghiệp',
    search_placeholder: 'Tìm kiếm...',
    menu_manage: 'Quản lý',
    menu_dashboard: 'Tổng quan',
    menu_members: 'Hội viên',
    menu_posts: 'Bài viết',
    menu_register: 'Đăng ký',
    menu_admin: 'Duyệt hội viên',
    menu_ai: 'Trợ lý AI',
    menu_system: 'Hệ thống',
    menu_settings: 'Cài đặt AI',
    lang_label: 'NGÔN NGỮ',
    stat_total_members: 'Tổng hội viên',
    stat_active: 'đang hoạt động',
    stat_pending: 'Chờ duyệt',
    stat_need_action: 'cần xử lý',
    stat_posts: 'Bài viết tháng này',
    stat_published: 'đã xuất bản',
    stat_events: 'Sự kiện sắp tới',
    stat_this_month: 'trong tháng này',
    section_new_members: 'Hội viên mới đăng ký',
    section_pending_posts: 'Bài chờ duyệt',
    btn_add: 'Thêm mới',
    notify_lang_switch: (n) => `Đã chuyển sang ${n}`,
    menu_directory: 'Danh mục đầy đủ',
    menu_tiers: 'Quyền lợi gói dịch vụ',
    menu_marketplace: 'Thị trường',
    menu_opportunities: 'Cơ hội giao thương',
    menu_national_feeds: 'Bảng tin toàn quốc',
    menu_events: 'Sự kiện',
    menu_guide: 'Hướng dẫn',
    menu_login: 'Đăng nhập',
    menu_logout: 'Đăng xuất',
    menu_welcome: 'Xin chào',
    hero_badge: 'Kết nối giao thương số 1 Việt Nam',
    hero_title: 'Kết nối doanh nghiệp, Cùng phát triển bền vững',
    hero_desc: 'AVG là cầu nối tin cậy giữa các doanh nghiệp hàng đầu. Tìm kiếm đối tác kinh doanh nhanh chóng, chia sẻ cơ hội đầu tư hợp tác và tiếp cận trợ lý AI nghiệp vụ thông minh 24/7.',
    hero_btn_register: 'Gia nhập ngay (Miễn phí)',
    hero_btn_explore: 'Khám phá hội viên',
    hero_realtime: 'Thời gian thực kết nối doanh nghiệp Việt',
    stat_active_members: 'Hội viên hoạt động',
    stat_verified_companies: 'Doanh nghiệp đã xác thực',
    stat_shared_opportunities: 'Cơ hội chia sẻ',
    stat_new_connections: 'Tin kết nối mới định kỳ',
    stat_diverse_companies: 'Doanh nghiệp đa dạng',
    stat_industries: 'Công nghệ, Sản xuất, Bán lẻ',
    stat_trade_events: 'Sự kiện giao thương',
    stat_annual_meetings: 'Hội nghị xúc tiến hàng năm',
    services_badge: 'Các dịch vụ chính',
    services_title: 'Giải pháp số hoá kết nối doanh nghiệp',
    services_desc: 'AVG cung cấp hạ tầng chuyển đổi số toàn diện để bạn giao thương, tìm đối tác và sử dụng Trợ lý AI phân tích sâu.',
    service_1_title: 'Kết nối Hội viên',
    service_1_desc: 'Kết nối hội viên, tiếp cận các doanh nghiệp lớn đã xác thực hồ sơ pháp nhân an toàn.',
    service_2_title: 'Bảng tin Cơ hội',
    service_2_desc: 'Tìm kiếm đối tác tiềm năng, bảng tin hội hỗ trợ kết nối dự án và cơ hội đầu tư hiệu quả.',
    service_3_title: 'Trợ lý AI thông minh',
    service_3_desc: 'Trợ lý AI nghiệp vụ trả lời thông tin tức thời, hỗ trợ tìm kiếm đối tác và đề xuất tự động.',
    service_4_title: 'Phân tích Thị trường',
    service_4_desc: 'Trợ lý AI thông minh phân tích xu hướng thị trường, tổng hợp dữ liệu giao dịch ngành.',
    featured_projects_title: 'Dự án kết nối nổi bật',
    featured_projects_desc: 'Tin đăng giao thương tiêu biểu được các hội viên đăng tải',
    btn_view_all_posts: 'Xem toàn bộ tin',
    featured_members_title: 'Hội viên nổi bật',
    featured_members_desc: 'Hội viên tiêu biểu được đề xuất hợp tác',
    btn_view_all_members: 'Xem danh mục hội viên',
    events_section_title: 'Giao lưu & Kết nối doanh nghiệp',
    events_section_desc: 'Các chương trình xúc tiến thương mại, hội thảo và gặp gỡ trực tiếp',
    btn_view_all_events: 'Xem tất cả sự kiện',
    pricing_section_title: 'Lựa chọn gói hội viên phù hợp',
    pricing_section_desc: 'Nâng cấp tài khoản để tiếp cận tệp đối tác rộng lớn hơn, đăng nhiều bài hơn và mở khóa quyền lợi AI đặc quyền.',
    tier_silver: 'Bạc',
    tier_gold: 'Vàng',
    tier_platinum: 'Bạch kim',
    price_free: 'Miễn phí',
    price_gold: '4.9 Mđ / năm',
    price_platinum: '9.9 Mđ / năm',
    btn_join_now: 'Gia nhập ngay',
    btn_upgrade_now: 'Đăng ký ngay',
    footer_desc: 'AVG là cầu nối tin cậy giữa các doanh nghiệp hàng đầu. Tìm kiếm đối tác kinh doanh nhanh chóng, chia sẻ cơ hội đầu tư, tự động kết nối doanh nghiệp Việt Nam 24/7.',
    footer_services: 'Dịch vụ',
    footer_support: 'Hỗ trợ',
    footer_contact: 'Liên hệ',
    footer_rights: '© Bảo lưu mọi quyền',
    label_popular: 'Phổ biến',
    label_elite: 'Thượng lưu',
    price_gold_val: '5.000.000đ',
    price_platinum_val: '15.000.000đ',
    pricing_per_year: 'năm',
    silver_feat_1: 'Hội viên hoạt động cơ bản',
    silver_feat_2: 'Hiển thị doanh nghiệp tại trang danh sách',
    silver_feat_3: 'Đăng tối đa 3 tin bài kết nối/tháng',
    silver_feat_4: 'Hỏi đáp Trợ lý AI cơ bản',
    gold_feat_1: 'Đầy đủ quyền lợi gói Silver',
    gold_feat_2: 'Ưu tiên hiển thị doanh nghiệp nổi bật',
    gold_feat_3: 'Đăng 15 tin bài kết nối/tháng',
    gold_feat_4: 'Mở rộng tương tác AI tự động kết nối',
    gold_feat_5: 'Nhận cơ hội giao thương đặc quyền',
    plat_feat_1: 'Quyền lợi cao cấp nhất hệ thống',
    plat_feat_2: 'Đăng tin giao thương không giới hạn',
    plat_feat_3: 'Tư vấn kết nối đối tác riêng biệt',
    plat_feat_4: 'Báo cáo phân tích thị trường chuyên sâu',
    plat_feat_5: 'Trợ lý AI riêng tùy biến cho thương hiệu',
    label_desc: 'Mô tả hoạt động',
    btn_read_more: 'Đọc bài viết',
    btn_read_post: 'Đọc bài',
    btn_view_details: 'Xem chi tiết',
    btn_back_to_feed: 'Quay lại Bảng tin',
    label_page: 'Trang',
    btn_back_prev: 'Trang trước',
    btn_go_next: 'Trang sau',
    label_show: 'Hiển thị',
    posts_title: 'Tin bài & Cơ hội giao thương',
    posts_subtitle: 'Cập nhật tin tức, cơ hội hợp tác kinh tế, tuyển dụng mới nhất từ các doanh nghiệp hội viên.',
    members_title: 'Thư mục doanh nghiệp hội viên',
    members_subtitle: 'Khám phá các doanh nghiệp thành viên đáng tin cậy trong mạng lưới AVG.',
    search_members_placeholder: 'Tìm tên, ngành, tỉnh thành...',
    search_posts_placeholder: 'Tìm bài viết, đối tác...',
    all_tiers: 'Tất cả hạng',
    all_industries: 'Tất cả ngành nghề',
    all_members: 'Tất cả hội viên',
    all_types: 'Tất cả phân loại',
    type_offer: 'Cung cấp sản phẩm',
    type_demand: 'Tìm kiếm / Nhu cầu',
    type_cooperate: 'Hợp tác phát triển',
    type_offer_short: 'Cung cấp',
    type_demand_short: 'Nhu cầu',
    type_cooperate_short: 'Hợp tác',
    posts_per_page: (count) => `${count} bài/trang`,
    members_per_page: (count) => `${count} thành viên`,
    found_members: (count) => `Tìm thấy ${count} hội viên`,
    found_posts: (count) => `Tìm thấy ${count} bài viết`,
    loading_posts: 'Đang tải bài viết...',
    loading_members: 'Đang tải danh sách hội viên...',
    no_posts_found: 'Không tìm thấy bài viết nào phù hợp với bộ lọc.',
    no_members_found: 'Không tìm thấy hội viên nào phù hợp với bộ lọc.',
    featured_members_header: 'Hội viên nổi bật được đề xuất',
    contact_login_required: 'Đăng nhập để hiển thị liên hệ',
    login_required_desc: 'Bạn cần đăng nhập để xem thông tin liên hệ trực tiếp của doanh nghiệp này.',
    login_now: 'Đăng nhập ngay',
    contact_info_label: 'Thông tin liên hệ',
    sidebar_author: 'ĐƠN VỊ ĐĂNG TẢI',
    location_default: 'Việt Nam',
    desc_default: 'Chưa có mô tả chi tiết hoạt động kinh doanh.',
    date_posted_label: 'Đăng ngày',
    category_default: 'Chung',
    badge_featured: 'Nổi bật',
    breadcrumb_home: 'Trang chủ',
    breadcrumb_opps: 'Bảng tin cơ hội',
    tier_platinum_partner: 'Đối tác Platinum',
    tier_platinum_members: 'Hội viên Platinum',
    tier_gold_members: 'Hội viên Gold',
    tier_silver_members: 'Hội viên Silver',
    translate_select_lang: 'Dịch sang',
    translate_button: 'Dịch nội dung (AI)',
    translate_view_original: 'Xem bản gốc (VI)',
    translate_view_original_short: 'Xem gốc'
  },
  en: {
    flag: '🇺🇸',
    label: 'EN',
    sb_sub: 'Member Management',
    search_placeholder: 'Search...',
    menu_manage: 'Management',
    menu_dashboard: 'Dashboard',
    menu_members: 'Members',
    menu_posts: 'Posts',
    menu_register: 'Register',
    menu_admin: 'Approve Members',
    menu_ai: 'AI Assistant',
    menu_system: 'System',
    menu_settings: 'AI Settings',
    lang_label: 'LANGUAGE',
    stat_total_members: 'Total members',
    stat_active: 'active',
    stat_pending: 'Pending',
    stat_need_action: 'need review',
    stat_posts: 'Posts this month',
    stat_published: 'published',
    stat_events: 'Upcoming events',
    stat_this_month: 'this month',
    section_new_members: 'New registrations',
    section_pending_posts: 'Posts awaiting review',
    btn_add: 'Add new',
    notify_lang_switch: (n) => `Switched to ${n}`,
    menu_directory: 'Full Directory',
    menu_tiers: 'Membership Tiers',
    menu_marketplace: 'Marketplace',
    menu_opportunities: 'Trade Opportunities',
    menu_national_feeds: 'National Opportunity Feeds',
    menu_events: 'Events',
    menu_guide: 'Guide',
    menu_login: 'Login',
    menu_logout: 'Logout',
    menu_welcome: 'Welcome',
    hero_badge: 'No.1 Business Connection Platform in Vietnam',
    hero_title: 'Connecting Businesses, Growing Sustainably Together',
    hero_desc: 'AVG is a trusted bridge between leading businesses. Instantly search for trade partners, share co-investment opportunities, and access the smart 24/7 AI Business Assistant.',
    hero_btn_register: 'Join Now (Free)',
    hero_btn_explore: 'Explore Members',
    hero_realtime: 'Realtime connections for Vietnamese enterprises',
    stat_active_members: 'Active Members',
    stat_verified_companies: 'Verified Enterprises',
    stat_shared_opportunities: 'Shared Opportunities',
    stat_new_connections: 'Periodic matching feeds',
    stat_diverse_companies: 'Diverse Industries',
    stat_industries: 'Tech, Manufacturing, Retail',
    stat_trade_events: 'Trade Events',
    stat_annual_meetings: 'Annual promotional meetings',
    services_badge: 'Core Services',
    services_title: 'Digital Solutions for B2B Matching',
    services_desc: 'AVG provides comprehensive digital infrastructure to help you trade, discover partners, and leverage AI analysis.',
    service_1_title: 'Member Connections',
    service_1_desc: 'Interact with registered members and approach large, verified legal enterprises safely.',
    service_2_title: 'Opportunity Feed',
    service_2_desc: 'Find potential trade partners, search project needs, and explore investment opportunities.',
    service_3_title: 'Smart AI Assistant',
    service_3_desc: 'Get instant replies from our AI advisor, offering automated recommendations for partners.',
    service_4_title: 'Market Analysis',
    service_4_desc: 'Leverage smart AI to monitor market trends and summarize industry trade insights.',
    featured_projects_title: 'Featured Matchings',
    featured_projects_desc: 'Outstanding trade and business opportunities shared by members',
    btn_view_all_posts: 'View All Feeds',
    featured_members_title: 'Featured Members',
    featured_members_desc: 'Outstanding members recommended for collaboration',
    btn_view_all_members: 'View All Members',
    events_section_title: 'Networking & Connection Events',
    events_section_desc: 'Trade promotions, business forums, and in-person matchmaking conferences',
    btn_view_all_events: 'View All Events',
    pricing_section_title: 'Select a Fitting Membership Tier',
    pricing_section_desc: 'Upgrade your subscription to reach larger partner databases, publish unlimited feeds, and unlock premium AI features.',
    tier_silver: 'Silver',
    tier_gold: 'Gold',
    tier_platinum: 'Platinum',
    price_free: 'Free',
    price_gold: '4.9M VND / year',
    price_platinum: '9.9M VND / year',
    btn_join_now: 'Join Now',
    btn_upgrade_now: 'Subscribe Now',
    footer_desc: 'AVG is a trusted bridge between leading businesses. Find partners quickly, share investment opportunities, and connect automatic matchmaking 24/7.',
    footer_services: 'Services',
    footer_support: 'Support',
    footer_contact: 'Contact',
    footer_rights: '© All rights reserved',
    label_popular: 'Popular',
    label_elite: 'Elite',
    price_gold_val: '$200',
    price_platinum_val: '$600',
    pricing_per_year: 'year',
    silver_feat_1: 'Basic membership access',
    silver_feat_2: 'Standard placement on member directory',
    silver_feat_3: 'Publish up to 3 matching posts / month',
    silver_feat_4: 'Standard AI Assistant Q&A access',
    gold_feat_1: 'All benefits of Silver tier included',
    gold_feat_2: 'Priority placement in featured directory',
    gold_feat_3: 'Publish up to 15 matching posts / month',
    gold_feat_4: 'Interactive AI matching automation',
    gold_feat_5: 'Access exclusive premium opportunities',
    plat_feat_1: 'Highest system access priority',
    plat_feat_2: 'Publish unlimited trade opportunities',
    plat_feat_3: 'Dedicated partner matching consulting',
    plat_feat_4: 'In-depth market research reports',
    plat_feat_5: 'Custom, brand-specific AI assistant',
    label_desc: 'Business Description',
    btn_read_more: 'Read post',
    btn_read_post: 'Read',
    btn_view_details: 'View details',
    btn_back_to_feed: 'Back to Feed',
    label_page: 'Page',
    btn_back_prev: 'Previous',
    btn_go_next: 'Next',
    label_show: 'Show',
    posts_title: 'Posts & Trade Opportunities',
    posts_subtitle: 'Get the latest news, trade opportunities, and recruitments from member enterprises.',
    members_title: 'Member Directory',
    members_subtitle: 'Explore trusted member businesses in the AVG network.',
    search_members_placeholder: 'Search by name, industry, city...',
    search_posts_placeholder: 'Search posts, partners...',
    all_tiers: 'All Tiers',
    all_industries: 'All Industries',
    all_members: 'All Members',
    all_types: 'All Types',
    type_offer: 'Offer / Provide',
    type_demand: 'Demand / Request',
    type_cooperate: 'Cooperation',
    type_offer_short: 'Offer',
    type_demand_short: 'Demand',
    type_cooperate_short: 'Cooperate',
    posts_per_page: (count) => `${count} posts/page`,
    members_per_page: (count) => `${count} members`,
    found_members: (count) => `Found ${count} members`,
    found_posts: (count) => `Found ${count} posts`,
    loading_posts: 'Loading posts...',
    loading_members: 'Loading members...',
    no_posts_found: 'No posts matching filters found.',
    no_members_found: 'No members matching filters found.',
    featured_members_header: 'Recommended Featured Members',
    contact_login_required: 'Login to display contact',
    login_required_desc: 'You need to log in to view the direct contact information of this business.',
    login_now: 'Login now',
    contact_info_label: 'Contact Information',
    sidebar_author: 'AUTHOR / PUBLISHER',
    location_default: 'Vietnam',
    desc_default: 'No business description provided.',
    date_posted_label: 'Posted date',
    category_default: 'General',
    badge_featured: 'Featured',
    breadcrumb_home: 'Home',
    breadcrumb_opps: 'Opportunity Feed',
    tier_platinum_partner: 'Platinum Partner',
    tier_platinum_members: 'Platinum Members',
    tier_gold_members: 'Gold Members',
    tier_silver_members: 'Silver Members',
    translate_select_lang: 'Translate to',
    translate_button: 'Translate (AI)',
    translate_view_original: 'View original (VI)',
    translate_view_original_short: 'View original'
  },
  zh: {
    flag: '🇨🇳',
    label: 'ZH',
    sb_sub: '会员管理',
    search_placeholder: '搜索...',
    menu_manage: '管理',
    menu_dashboard: '总览',
    menu_members: '会员',
    menu_posts: '文章',
    menu_register: '注册',
    menu_admin: '审核会员',
    menu_ai: 'AI助手',
    menu_system: '系统',
    menu_settings: 'AI设置',
    lang_label: '语言',
    stat_total_members: '总会员数',
    stat_active: '活跃',
    stat_pending: '待审核',
    stat_need_action: '需处理',
    stat_posts: '本月文章',
    stat_published: '已发布',
    stat_events: '即将举办',
    stat_this_month: '本月',
    section_new_members: '新注册会员',
    section_pending_posts: '待审文章',
    btn_add: '新增',
    notify_lang_switch: (n) => `已切换到${n}`,
    menu_directory: '全部名录',
    menu_tiers: '会员权益',
    menu_marketplace: '市场交易',
    menu_opportunities: '商业机会',
    menu_national_feeds: '全国看板',
    menu_events: '活动机会',
    menu_guide: '使用指南',
    menu_login: '登录',
    menu_logout: '退出',
    menu_welcome: '欢迎',
    hero_badge: '越南第一的企业对接平台',
    hero_title: '连接企业，携手共赢可持续发展',
    hero_desc: 'AVG是领先企业之间值得信赖的桥梁。快速搜索贸易伙伴，分享共同投资机会，并使用24/7智能AI业务助手。',
    hero_btn_register: '立即加入（免费）',
    hero_btn_explore: '探索会员',
    hero_realtime: '实时对接越南企业',
    stat_active_members: '活跃会员',
    stat_verified_companies: '已核验企业',
    stat_shared_opportunities: '共享商机',
    stat_new_connections: '定期发布的商业对接',
    stat_diverse_companies: '多元化行业',
    stat_industries: '科技、制造、零售',
    stat_trade_events: '贸易活动',
    stat_annual_meetings: '年度贸易推介会议',
    services_badge: '核心服务',
    services_title: 'B2B智能对接数字解决方案',
    services_desc: 'AVG提供全面的数字化基础架构，帮助您进行贸易、发现合作伙伴并利用AI分析。',
    service_1_title: '会员对接',
    service_1_desc: '与注册会员互动，安全地接触已验证的法人实体企业。',
    service_2_title: '商机看板',
    service_2_desc: '寻找潜在的贸易伙伴，搜索项目需求，并探索投资机会。',
    service_3_title: '智能AI助手',
    service_3_desc: '从我们的AI业务顾问那里获得即时答复，提供自动匹配的合作伙伴推荐。',
    service_4_title: '市场分析',
    service_4_desc: '利用智能AI监控市场趋势并总结行业贸易洞察。',
    featured_projects_title: '热门对接项目',
    featured_projects_desc: '会员发布的优秀贸易和商业机会',
    btn_view_all_posts: '查看全部看板',
    featured_members_title: '优秀会员',
    featured_members_desc: '推荐合作的杰出会员企业',
    btn_view_all_members: '查看会员名录',
    events_section_title: '商务交流与对接活动',
    events_section_desc: '贸易推介、商业论坛和线下对接会',
    btn_view_all_events: '查看全部活动',
    pricing_section_title: '选择合适的会员等级',
    pricing_section_desc: '升级您的会员级别，接触更庞大的合作伙伴数据库，发布无限看板并解锁高级AI功能。',
    tier_silver: '银牌',
    tier_gold: '金牌',
    tier_platinum: '白金牌',
    price_free: '免费',
    price_gold: '490万 越南盾 / 年',
    price_platinum: '990万 越南盾 / 年',
    btn_join_now: '立即加入',
    btn_upgrade_now: '立即订阅',
    footer_desc: 'AVG是领先企业之间值得信赖的桥梁。快速寻找合作伙伴，分享投资商机，并实现24/7自动对接。',
    footer_services: '服务',
    footer_support: '支持',
    footer_contact: '联系我们',
    footer_rights: '© 版权所有 保留所有权利',
    label_popular: '热门',
    label_elite: '至尊',
    price_gold_val: '¥1,400',
    price_platinum_val: '¥4,200',
    pricing_per_year: '年',
    silver_feat_1: '基础会员权限',
    silver_feat_2: '标准会员名录展示',
    silver_feat_3: '每月发布最多 3 篇对接信息',
    silver_feat_4: '基础 AI 助手问答服务',
    gold_feat_1: '包含银牌会员的所有权益',
    gold_feat_2: '在优秀名录中优先展示',
    gold_feat_3: '每月发布最多 15 篇对接信息',
    gold_feat_4: '智能 AI 互动对接自动化',
    gold_feat_5: '获取专属优质贸易商机',
    plat_feat_1: '系统最高优先级权限',
    plat_feat_2: '无限制发布贸易对接信息',
    plat_feat_3: '一对一专属合作伙伴匹配服务',
    plat_feat_4: '深度行业 market research reports',
    plat_feat_5: '定制化品牌专属 AI 助手',
    label_desc: '业务描述',
    btn_read_more: '阅读文章',
    btn_read_post: '阅读',
    btn_view_details: '查看详情',
    btn_back_to_feed: '返回看板',
    label_page: '页',
    btn_back_prev: '上一页',
    btn_go_next: '下一页',
    label_show: '显示',
    posts_title: '文章与贸易机会',
    posts_subtitle: '从会员企业获取最新新闻、贸易机会和招聘信息。',
    members_title: '会员名录',
    members_subtitle: '探索AVG网络中值得信赖的会员企业。',
    search_members_placeholder: '按名称、行业、城市搜索...',
    search_posts_placeholder: '搜索文章、合作伙伴...',
    all_tiers: '所有级别',
    all_industries: '所有行业',
    all_members: '所有会员',
    all_types: '所有类型',
    type_offer: '供应 / 提供',
    type_demand: '需求 / 寻求',
    type_cooperate: '合作',
    type_offer_short: '供应',
    type_demand_short: '需求',
    type_cooperate_short: '合作',
    posts_per_page: (count) => `${count} 篇/页`,
    members_per_page: (count) => `${count} 会员`,
    found_members: (count) => `找到 ${count} 个会员`,
    found_posts: (count) => `找到 ${count} 篇文章`,
    loading_posts: '正在加载文章...',
    loading_members: '正在加载会员列表...',
    no_posts_found: '没有找到匹配的广告。',
    no_members_found: '没有找到匹配的会员。',
    featured_members_header: '推荐优秀会员',
    contact_login_required: '登录以显示联系方式',
    login_required_desc: '您需要登录才能查看该企业的直接联系方式。',
    login_now: '立即登录',
    contact_info_label: '联系方式',
    sidebar_author: '发布单位',
    location_default: '越南',
    desc_default: '尚无详细业务描述。',
    date_posted_label: '发布日期',
    category_default: '常规',
    badge_featured: '精选',
    breadcrumb_home: '首页',
    breadcrumb_opps: '商机看板',
    tier_platinum_partner: '白金合作伙伴',
    tier_platinum_members: '白金会员',
    tier_gold_members: '黄金会员',
    tier_silver_members: '白银会员',
    translate_select_lang: '翻译为',
    translate_button: 'AI翻译',
    translate_view_original: '查看原文 (VI)',
    translate_view_original_short: '查看原文'
  },
  ja: {
    flag: '🇯🇵',
    label: 'JA',
    sb_sub: '会員管理',
    search_placeholder: '検索...',
    menu_manage: '管理',
    menu_dashboard: 'ダッシュボード',
    menu_members: '会員',
    menu_posts: '投稿',
    menu_register: '登録',
    menu_admin: '会員承認',
    menu_ai: 'AIアシスタント',
    menu_system: 'システム',
    menu_settings: 'AI設定',
    lang_label: '言語',
    stat_total_members: '総会員数',
    stat_active: 'アクティブ',
    stat_pending: '承認待ち',
    stat_need_action: '要対応',
    stat_posts: '今月の投稿',
    stat_published: '公開済み',
    stat_events: '今後のイベント',
    stat_this_month: '今月',
    section_new_members: '新規会員',
    section_pending_posts: '承認待ち記事',
    btn_add: '新規追加',
    notify_lang_switch: (n) => `${n}に切り替えました`,
    menu_directory: 'フルディレクトリ',
    menu_tiers: '会員特典',
    menu_marketplace: 'マーケット',
    menu_opportunities: 'ビジネス機会',
    menu_national_feeds: '全国フィード',
    menu_events: 'イベント',
    menu_guide: 'ガイド',
    menu_login: 'ログイン',
    menu_logout: 'ログアウト',
    menu_welcome: 'ようこそ',
    hero_badge: 'ベトナムNo.1ビジネス・マッチング・プラットフォーム',
    hero_title: '企業を繋ぎ、共に持続可能な成長へ',
    hero_desc: 'AVGは大手企業間の信頼できる架け橋です。ビジネスパートナーを迅速に検索し、共同投資の機会を共有し、24時間年中無休のスマートAIアシスタントにアクセスします。',
    hero_btn_register: '今すぐ参加（無料）',
    hero_btn_explore: '会員を見つける',
    hero_realtime: 'ベトナム企業のリアルタイム・マッチング',
    stat_active_members: 'アクティブ会員',
    stat_verified_companies: '認証済み企業',
    stat_shared_opportunities: '共有案件',
    stat_new_connections: '定期的なマッチングフィード',
    stat_diverse_companies: '多様な業界',
    stat_industries: 'IT、製造、小売',
    stat_trade_events: 'ビジネスイベント',
    stat_annual_meetings: '年次プロモーション会議',
    services_badge: 'コアサービス',
    services_title: 'B2Bマッチングのデジタルソリューション',
    services_desc: 'AVGは、取引、パートナーの開拓、AI分析の活用を支援する包括的なデジタルインフラを提供します。',
    service_1_title: '会員接続',
    service_1_desc: '登録会員と交流し、認証済みの安全な法人企業にアプローチします。',
    service_2_title: '案件フィード',
    service_2_desc: '潜在的なパートナーを検索し、プロジェクトニーズを確認し、投資機会を探ります。',
    service_3_title: 'スマートAI助手',
    service_3_desc: 'AIアドバイザーから即座に回答を得て、最適なパートナーの自動提案を受けます。',
    service_4_title: '市場分析',
    service_4_desc: 'スマートAIを活用して市場動向を監視し、業界の取引動向を要約します。',
    featured_projects_title: '注目のマッチング案件',
    featured_projects_desc: '会員から共有された優れた取引およびビジネス案件',
    btn_view_all_posts: 'すべてのフィードを表示',
    featured_members_title: '注目の会員',
    featured_members_desc: 'コラボレーションに推奨される優れた会員企業',
    btn_view_all_members: '会員名録を表示',
    events_section_title: 'ネットワーキング＆マッチングイベント',
    events_section_desc: '貿易プロモーション、ビジネスフォーラム、対面式マッチング会議',
    btn_view_all_events: 'すべてのイベントを表示',
    pricing_section_title: '最適なメンバーシッププランを選択',
    pricing_section_desc: 'プランをアップグレードして、より大きなパートナーデータベースにアクセスし、無制限のフィードを公開し、プレミアムAI機能のロックを解除します。',
    tier_silver: 'シルバー',
    tier_gold: 'ゴールド',
    tier_platinum: 'プラチナ',
    price_free: '無料',
    price_gold: '490万 ドン / 年',
    price_platinum: '990万 ドン / 年',
    btn_join_now: '今すぐ登録',
    btn_upgrade_now: '今すぐ申し込む',
    footer_desc: 'AVGは大手企業間の信頼できる架け橋です。パートナーを素早く見つけ、投資機会を共有し、24時間365日の自動マッチングを接続します。',
    footer_services: 'サービス',
    footer_support: 'サポート',
    footer_contact: 'お問い合わせ',
    footer_rights: '© All rights reserved. 無断転載を禁じます',
    label_popular: '人気',
    label_elite: 'エリート',
    price_gold_val: '¥31,000',
    price_platinum_val: '¥93,000',
    pricing_per_year: '年',
    silver_feat_1: 'ベーシックメンバーシップ権限',
    silver_feat_2: '標準会員ディレクトリ掲載',
    silver_feat_3: '月間最大3件の案件公開',
    silver_feat_4: '標準的なAIアシスタントQ&Aアクセス',
    gold_feat_1: 'シルバープランの全特典を含む',
    gold_feat_2: '注目の会員枠に優先表示',
    gold_feat_3: '月間最大15件の案件公開',
    gold_feat_4: 'スマートAIマッチングの自動化',
    gold_feat_5: '限定プレミアム案件へのアクセス',
    plat_feat_1: 'システム最高の優先アクセス権',
    plat_feat_2: '無制限の取引案件の公開',
    plat_feat_3: '専任パートナーマッチング相談',
    plat_feat_4: '詳細な業界市場調査レポート',
    plat_feat_5: 'カスタムブランド専用AIアシスタント',
    label_desc: '事業内容',
    btn_read_more: '記事を読む',
    btn_read_post: '読む',
    btn_view_details: '詳細を見る',
    btn_back_to_feed: 'フィードに戻る',
    label_page: 'ページ',
    btn_back_prev: '前へ',
    btn_go_next: '次へ',
    label_show: '表示',
    posts_title: '投稿とビジネス機会',
    posts_subtitle: '会員企業からの最新ニュース、貿易機会、採用情報を取得します。',
    members_title: '会員名録',
    members_subtitle: 'AVGネットワーク内の信頼できる会員企業を探索します。',
    search_members_placeholder: '名前、業界、都市で検索...',
    search_posts_placeholder: '投稿、パートナーを検索...',
    all_tiers: 'すべての階級',
    all_industries: 'すべての業界',
    all_members: 'すべての会員',
    all_types: 'すべてのタイプ',
    type_offer: '提供',
    type_demand: '需要',
    type_cooperate: '協力',
    type_offer_short: '提供',
    type_demand_short: '需要',
    type_cooperate_short: '協力',
    posts_per_page: (count) => `${count} 記事/ページ`,
    members_per_page: (count) => `${count} 会員`,
    found_members: (count) => `${count} 会員が見つかりました`,
    found_posts: (count) => `${count} 記事が見つかりました`,
    loading_posts: '投稿を読み込んでいます...',
    loading_members: '会員リストを読み込んでいます...',
    no_posts_found: 'フィルターに一致する投稿が見つかりませんでした。',
    no_members_found: 'フィルターに一致する会員が見つかりませんでした。',
    featured_members_header: 'おすすめの注目会員',
    contact_login_required: 'ログインして連絡先を表示',
    login_required_desc: 'このビジネスの直接の連絡先情報を表示するにはログインする必要があります。',
    login_now: '今すぐログイン',
    contact_info_label: '連絡先情報',
    sidebar_author: '投稿元',
    location_default: 'ベトナム',
    desc_default: 'ビジネスの説明はありません。',
    date_posted_label: '投稿日',
    category_default: '一般',
    badge_featured: '注目',
    breadcrumb_home: 'ホーム',
    breadcrumb_opps: 'フィード',
    tier_platinum_partner: 'プラチナパートナー',
    tier_platinum_members: 'プラチナ会員',
    tier_gold_members: 'ゴールド会員',
    tier_silver_members: 'シルバー会員',
    translate_select_lang: '翻訳先',
    translate_button: 'AI翻訳',
    translate_view_original: '原文を表示 (VI)',
    translate_view_original_short: '原文表示'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('avg_lang') || 'vi';
  });

  const t = (key) => {
    const langObj = LANGS[currentLang] || LANGS.vi;
    const value = langObj[key] || LANGS.vi[key];
    if (typeof value === 'function') return value;
    return value || key;
  };

  const changeLang = (lang) => {
    if (LANGS[lang]) {
      setCurrentLang(lang);
      localStorage.setItem('avg_lang', lang);
    }
  };

  const getLangDetails = () => LANGS[currentLang] || LANGS.vi;

  return (
    <LanguageContext.Provider value={{ currentLang, t, changeLang, getLangDetails, LANGS }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => useContext(LanguageContext);
